// Login.js
import React, { useContext, useState } from 'react';
import { useHistory } from 'react-router-dom';
import { AlertsContext } from '../Context/AlertsState';
import Alerts from './Alerts';

export default function Login() {
  const localhost = "http://localhost:4000";
  const history = useHistory();
  const [loginData, setLoginData] = useState({
    email: '',
    password: ''
  });

  const { showAlert } = useContext(AlertsContext); // Access showAlert function from context

  const onChange = (e) => {
    setLoginData({ ...loginData, [e.target.name]: e.target.value });
  };

  const handleSubmit = async (e) => {
    e.preventDefault();

    const response = await fetch(`${localhost}/login`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({ email: loginData.email, password: loginData.password })
    });

    const json = await response.json();
    console.log(json);

    if (json.success) {
      // Saving the Auth Token generated by JWT while Login in localStorage 
      localStorage.setItem('token', json.authenticationToken);
      showAlert('Login Successful.', 'success'); // Show success alert
      history.push("/");
    } else {
      showAlert('Invalid Credentials.', 'danger'); // Show danger alert
      history.push("/login");
    }
  };

  return (
    <>
      <Alerts /> {/* Render the Alerts component to display alerts */}
      
      <form onSubmit={handleSubmit}>
        <div className="mb-3">
          <label htmlFor="email" className="form-label">Email address</label>
          <input type="email" className="form-control" id="email" value={loginData.email} onChange={onChange} />
        </div>
        <div className="mb-3">
          <label htmlFor="password" className="form-label">Password</label>
          <input type="password" className="form-control" id="password" value={loginData.password} onChange={onChange} />
        </div>
        <button type="submit" className="btn btn-primary">Submit</button>
      </form>
    </>
  );
}
