import React, { useContext, useState } from 'react'
import useHistory from 'react-router-dom'
import { AlertsContext } from '../Context/AlertsState'
import Alerts from './Alerts'
export default function Signup() {

const [signupData, setSignupData]= useState({
    name:'',
    email:'',
    password:'',
    cpassword:'',
})

const handleChaange=(e)=>{
    setSignupData({...signupData,[e.target.name]:[e.target.value]})
}

const loaclhost = "http://localhost:4000";
let history = useHistory();
const {showAlert}= useContext(AlertsContext);
const handleSubmit =async(e)=>{
    e.preventDefault();

    const response= await fetch(`${loaclhost}/signup`,{
        method:'POST',
        headers:{
            'Content-Type':'application/json'
        },
        body:JSON.stringify({name:signupData.name, email:signupData.email, password:signupData.password})
    });

    const json = await response.json();
    console.log(json);
    if(json.success== true){
        // Saving the Auth Token generated by JWT while Login in a local stroage 
        localStorage.setItem('token', json.authenticationToken);
        history.push("/")
        showAlert('Registered Successfully', 'success'); // Show success alert


    }
    else{ 
        history.push("/login")
        showAlert('Something went wrong', 'success'); // Show danger alert
    }
}
  return (
    <>
    <Alerts/>
    <div className="container">
    <form onSubmit={handleSubmit}>
        <div className="mb-3">
            <label htmlFor="name" className="form-label">Email address</label>
            <input type="text" className="form-control" id="name" value={signupData.name} aria-describedby="emailHelp"/>
        </div>
        <div className="mb-3">
            <label htmlFor="exampleInputEmail1" className="form-label">Email address</label>
            <input type="email" onChange={handleChaange} value={signupData.email}className="form-control" id="exampleInputEmail1" aria-describedby="emailHelp"/>
        </div>
        <div className="mb-3">
            <label htmlFor="password" className="form-label">Password</label>
            <input type="password" onChange={handleChaange} value={signupData.password} className="form-control" id="password"/>
        </div>
        <div className="mb-3">
            <label htmlFor="confirmpassword" className="form-label">Confirm Password</label>
            <input type="password" onChange={handleChaange} value={signupData.cpassword} className="form-control" id="confirmpassword"/>
        </div>
        <button type="submit" className="btn btn-primary">Submit</button>
    </form>
    </div>
    </>
  )
}
